modLoader = "javafml"
# JavaFML/Forge major for 1.20.x starts at 47. Using an upper cap before 50 keeps it on 1.20.x lines only.
loaderVersion = "[47,50)"

license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

# ---- Dependencies ----

# Forge itself
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
# Forge 47.x–49.x covers MC 1.20.1–1.20.4 lines. Bump upper bound if you add newer 1.20.x lines.
versionRange = "[47,50)"
ordering = "NONE"
side = "BOTH"

# Minecraft
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
# Any 1.20.* but not 1.21
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
